//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Product_tag { get; set; }
        public Nullable<bool> Invoice_tag { get; set; }
        public Nullable<bool> Warehouse_tag { get; set; }
        public Nullable<bool> User_tag { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
